CREATE SEQUENCE `id_seq` start with 1 minvalue 1 maxvalue 9223372036854775806 increment by 100 cache 1000 nocycle ENGINE=InnoDB;

CREATE TABLE `CrossSectionData` (
  `id` int(11) NOT NULL,
  `crosssectioninfo_key` int(11) NOT NULL,
  `MT` smallint(6) NOT NULL,
  `Energy` float NOT NULL COMMENT 'eV',
  `CrossSection` float NOT NULL COMMENT 'barns',
  PRIMARY KEY (`id`),
  KEY `ix_crosssectioninfo` (`crosssectioninfo_key`),
  KEY `ix_crosssectioninfo_MT` (`MT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `CrossSectionInfo` (
  `id` int(11) NOT NULL,
  `MT` smallint(6) NOT NULL,
  `material_key` int(11) NOT NULL,
  `library_key` int(11) NOT NULL,
  `ZA` int(11) NOT NULL,
  `AWR` float NOT NULL,
  `QM` float NOT NULL COMMENT 'Mass-difference Q value (eV): defined as the mass of the projectile and the ground state of the target minus the mass of the residual nucleus in the ground state and masses of all other reaction products',
  `QI` float NOT NULL COMMENT 'Reaction Q value for the (lowest energy) states defined by the given MT value in a simple two-body reaction or a breakup reaction',
  `LR` mediumint(9) NOT NULL COMMENT 'Complex or “breakup” reaction flag, which indicates that additional particles not specified by the MT number will be emitted',
  `NR` smallint(6) NOT NULL,
  `NP` mediumint(9) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_crosssection_mt_mat_lib` (`MT`,`material_key`,`library_key`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;;

CREATE TABLE `GeneralInfo` (
  `id` int(11) NOT NULL,
  `material_key` int(11) NOT NULL,
  `library_key` int(11) NOT NULL,
  `file_key` int(11) NOT NULL,
  `LRP` tinyint(4) NOT NULL COMMENT 'Flag indicating whether resolved and/or unresolved resonance parameters are given in File 2',
  `NMOD` smallint(6) NOT NULL COMMENT 'Modification number for this material',
  `AWI` float NOT NULL COMMENT 'Mass of the projectile in neutron mass units. For incident photons or decay data sub-libraries, use AWI=0',
  `EMAX` float NOT NULL COMMENT 'Upper limit of the energy range for evaluation.',
  `TEMP` float NOT NULL COMMENT 'Target temperature (Kelvin) for data that have been generated by Doppler broadening. For derived data only; use TEMP=0.0 for all primary evaluations.',
  `LDRV` smallint(6) NOT NULL COMMENT 'Special derived material flag that distinguishes between different evaluations with the same material keys (i.e., MAT, NMOD, NSUB): LDRV=0, primary evaluation: LDRV≥ 1, special derived evaluation (for example, a dosimetry evaluation using sections (MT) extracted from the primary evaluation).',
  `Description` MEDIUMTEXT NOT NULL,
  `ZSYMAM` varchar(30) DEFAULT NULL COMMENT 'Character representation of the material defined by the atomic number, chemical symbol, atomic mass number, and metastable state designation in the form Z-cc-AM',
  `ALAB` varchar(30) DEFAULT NULL COMMENT 'Mnemonic for the originating laboratory(s)',
  `EDATE` varchar(30) DEFAULT NULL COMMENT 'Date of evaluation given in the form “EVAL-DEC74”',
  `AUTH` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL COMMENT 'Author(s) name(s)',
  `REF` varchar(30) DEFAULT NULL COMMENT 'Primary reference for the evaluation',
  `DDATE` varchar(30) DEFAULT NULL COMMENT 'Original distribution date',
  `RDATE` varchar(30) DEFAULT NULL COMMENT 'Date and number of the last revision to this evaluation',
  `ENDATE` varchar(30) DEFAULT NULL COMMENT 'Master File entry date in the form yyyymmdd',
  `HSUB` varchar(500) DEFAULT NULL COMMENT 'Identifier for the library contained on three successive records',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_GeneralInfo_mat_lib` (`material_key`,`library_key`),
  KEY `ix_GeneralInfo_filekey` (`file_key`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

CREATE TABLE `Library` (
  `id` int(11) NOT NULL,
  `NLIB` tinyint(4) NOT NULL COMMENT 'Library',
  `NVER` smallint(6) NOT NULL COMMENT 'Version. one of the periodic updates to a library in ENDF format (e.g., NVER=7 for ENDF/B-VII). A change of version may imply a change in format, standards, and/or procedures',
  `LREL` smallint(6) NOT NULL COMMENT 'Release. library release number of an intermediate release containing minor updates and corrections of errors after a general release of a library. A release number is appended to the library/version name for each succeeding revision of the data set(e.g., ENDF/B-VI.2 for Release 2 of the ENDF/B-VI library).',
  `NSUB` smallint(6) NOT NULL COMMENT 'Sublibrary. NSUB = 10*IPART+ITYPE',
  `NFOR` tinyint(4) NOT NULL COMMENT 'Format. format in which the data is tabulated; tells the processing codes how to read the subsequent data records (e.g., NFOR=6 for ENDF-6).',
  `IPART` smallint(6) NOT NULL COMMENT 'IPART=1000*Z+A defines the incident particle; use IPART=0 for incident photons or no incident particle (decay data), use IPART=11 for incident electrons, and IPART=0 for photo-atomic or electro-atomic data',
  `ITYPE` tinyint(4) NOT NULL,
  `Definition` varchar(200) DEFAULT NULL,
  `SublibraryName` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;;

CREATE TABLE `Material` (
  `id` int(11) NOT NULL,
  `MAT` smallint(6) NOT NULL,
  `Z` tinyint(4) NOT NULL COMMENT 'Charge number',
  `A` smallint(6) NOT NULL COMMENT 'Mass number',
  `AWR` decimal(12,9) NOT NULL COMMENT 'Mass relative to neutron',
  `LFI` tinyint(4) NOT NULL COMMENT 'Flag indicating whether this material fissions: LFI=0, this material does not fission; LFI=1, this material fissions.',
  `LIS` tinyint(4) UNSIGNED NOT NULL COMMENT 'State number of the target nucleus. The ground state is indicated by LIS=0.',
  `LISO` tinyint(4) NOT NULL COMMENT 'Isomeric state number. The ground state is indicated by LISO=0. LIS is greater than or equal to LISO.',
  `ELIS` float NOT NULL COMMENT 'Excitation energy of the target nucleus relative to 0.0 for the ground state',
  `STA` tinyint(4) NOT NULL COMMENT 'Target stability flag: STA=0, stable nucleus; STA=1 unstable nucleus. If the target is unstable, radioactive decay data should be given in the decay data sub-library (NSUB=4).',
  `Description` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_MAT` (`MAT`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;;

CREATE TABLE `Directory` (
  `id` int(11) NOT NULL,
  `general_info_key` int(11) NOT NULL,
  `MF` tinyint(4) NOT NULL,
  `MT` smallint(6) NOT NULL,
  `NC` mediumint(9) NOT NULL,
  `Modification` smallint(6) NOT NULL COMMENT 'MOD',
  PRIMARY KEY (`id`),
  KEY `general_info_key` (`general_info_key`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;;

CREATE TABLE `Files` (
  `id` int(11) NOT NULL,
  `path` varchar(200) NOT NULL,
  `name` varchar(200) NOT NULL,
  `zip_file` varchar(200) DEFAULT NULL,
  `comment` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;;

CREATE TABLE `Interpolation` (
  `id` int(11) NOT NULL,
  `info_key` int(11) NOT NULL,
  `MT` int(11) NOT NULL,
  `MF` int(11) NOT NULL,
  `NBT` mediumint(9) NOT NULL,
  `InterpolationScheme` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_interp_info_MT_MF` (`info_key`,`MT`,`MF`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;;

